apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sonarqube.installPlugins.configMap" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations:
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  install_plugins.sh: |-
    {{- if .Values.plugins.install }}
    mkdir /bitnami/sonarqube-extensions/plugins
    mkdir  /bitnami/sonarqube-extensions/data
    [ -e /bitnami/sonarqube-extensions/plugins/* ] && rm /bitnami/sonarqube/extensions/plugins/*
    cd /bitnami/sonarqube-extensions/plugins
      {{- range $index, $val := .Values.plugins.install }}
    curl {{ if $.Values.plugins.noCheckCertificate }}--insecure{{ end }} {{ if $.Values.plugins.netrcCreds }}--netrc-file /root/.netrc{{ end }} -fsSLO {{ $val | quote }}
      {{- end }}
    {{- end }}
